"""esquema inicial

Revision ID: 94451af50953
Revises:
Create Date: 2026-08-08 04:29:52.504805
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "94451af50953"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "objeto_afectado",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nombre_tabla", sa.String(length=100), nullable=False),
        sa.Column("descripcion", sa.String(length=255), nullable=True),
        sa.Column(
            "fecha_creado",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("fecha_actualizado", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "rol",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nombre", sa.String(length=100), nullable=False),
        sa.Column("descripcion", sa.String(length=255), nullable=True),
        sa.Column(
            "fecha_creado",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("fecha_actualizado", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("nombre"),
    )
    op.create_table(
        "tipo_accion",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nombre", sa.String(length=100), nullable=False),
        sa.Column("descripcion", sa.String(length=255), nullable=True),
        sa.Column(
            "fecha_creado",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("fecha_actualizado", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "tipo_dispositivo",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nombre", sa.String(length=100), nullable=False),
        sa.Column("descripcion", sa.String(length=255), nullable=True),
        sa.Column(
            "fecha_creado",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("fecha_actualizado", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "tipo_documento",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nombre", sa.String(length=100), nullable=False),
        sa.Column("acronimo", sa.String(length=10), nullable=True),
        sa.Column("descripcion", sa.String(length=255), nullable=True),
        sa.Column(
            "fecha_creado",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("fecha_actualizado", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "tipo_registro",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nombre", sa.String(length=100), nullable=False),
        sa.Column("descripcion", sa.String(length=255), nullable=True),
        sa.Column(
            "fecha_creado",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("fecha_actualizado", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "tipo_reporte",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nombre", sa.String(length=100), nullable=False),
        sa.Column("descripcion", sa.String(length=255), nullable=True),
        sa.Column(
            "fecha_creado",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("fecha_actualizado", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "usuario",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nombres", sa.String(length=100), nullable=False),
        sa.Column("apellidos", sa.String(length=100), nullable=False),
        sa.Column("id_tipo_documento", sa.Integer(), nullable=False),
        sa.Column("documento", sa.String(length=50), nullable=False),
        sa.Column("direccion", sa.String(length=255), nullable=True),
        sa.Column("contrasena_hash", sa.String(length=255), nullable=False),
        sa.Column(
            "fecha_creado",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("fecha_actualizado", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["id_tipo_documento"],
            ["tipo_documento.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("documento"),
    )
    op.create_table(
        "auditoria_negocio",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("id_tipo_registro", sa.Integer(), nullable=False),
        sa.Column("registrado_por", sa.Integer(), nullable=False),
        sa.Column("ejemplo_data", sa.String(length=500), nullable=True),
        sa.Column(
            "fecha_creado",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("fecha_actualizado", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["id_tipo_registro"],
            ["tipo_registro.id"],
        ),
        sa.ForeignKeyConstraint(
            ["registrado_por"],
            ["usuario.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "dispositivo",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("serial", sa.String(length=50), nullable=False),
        sa.Column("marca", sa.String(length=100), nullable=False),
        sa.Column("modelo", sa.String(length=100), nullable=False),
        sa.Column("sistema", sa.String(length=50), nullable=True),
        sa.Column("id_tipo_dispositivo", sa.Integer(), nullable=False),
        sa.Column("id_usuario", sa.Integer(), nullable=False),
        sa.Column("fecha_url", sa.String(length=255), nullable=True),
        sa.Column("qr", sa.String(length=255), nullable=True),
        sa.Column(
            "fecha_creado",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("fecha_actualizado", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["id_tipo_dispositivo"],
            ["tipo_dispositivo.id"],
        ),
        sa.ForeignKeyConstraint(
            ["id_usuario"],
            ["usuario.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("serial"),
    )
    op.create_table(
        "log_sistema",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("id_accion", sa.Integer(), nullable=False),
        sa.Column("id_usuario", sa.Integer(), nullable=False),
        sa.Column("id_objeto_afectado", sa.Integer(), nullable=False),
        sa.Column("iv_firma", sa.String(length=255), nullable=True),
        sa.Column(
            "fecha_creado",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("fecha_actualizado", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["id_accion"],
            ["tipo_accion.id"],
        ),
        sa.ForeignKeyConstraint(
            ["id_objeto_afectado"],
            ["objeto_afectado.id"],
        ),
        sa.ForeignKeyConstraint(
            ["id_usuario"],
            ["usuario.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "reporte",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("generado_por", sa.Integer(), nullable=False),
        sa.Column("filtros_aplicados", sa.String(length=255), nullable=True),
        sa.Column("url_archivo", sa.String(length=255), nullable=True),
        sa.Column("id_tipo_reporte", sa.Integer(), nullable=False),
        sa.Column(
            "fecha_creado",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("fecha_actualizado", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["generado_por"],
            ["usuario.id"],
        ),
        sa.ForeignKeyConstraint(
            ["id_tipo_reporte"],
            ["tipo_reporte.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "usuario_rol",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("id_usuario", sa.Integer(), nullable=False),
        sa.Column("id_rol", sa.Integer(), nullable=False),
        sa.Column(
            "fecha_creado",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("fecha_actualizado", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["id_rol"],
            ["rol.id"],
        ),
        sa.ForeignKeyConstraint(
            ["id_usuario"],
            ["usuario.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id_usuario", "id_rol"),
    )
    op.create_table(
        "consulta_reporte",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("entidad_consultada", sa.String(length=100), nullable=False),
        sa.Column("filtro_aplicado", sa.String(length=255), nullable=True),
        sa.Column("id_reporte", sa.Integer(), nullable=False),
        sa.Column(
            "fecha_creado",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("fecha_actualizado", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["id_reporte"],
            ["reporte.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "log_detalle",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("id_log", sa.Integer(), nullable=False),
        sa.Column("campo_afectado", sa.String(length=100), nullable=False),
        sa.Column("valor_anterior", sa.String(length=255), nullable=True),
        sa.Column("valor_nuevo", sa.String(length=255), nullable=True),
        sa.Column(
            "fecha_creado",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("fecha_actualizado", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["id_log"],
            ["log_sistema.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("log_detalle")
    op.drop_table("consulta_reporte")
    op.drop_table("usuario_rol")
    op.drop_table("reporte")
    op.drop_table("log_sistema")
    op.drop_table("dispositivo")
    op.drop_table("auditoria_negocio")
    op.drop_table("usuario")
    op.drop_table("tipo_reporte")
    op.drop_table("tipo_registro")
    op.drop_table("tipo_documento")
    op.drop_table("tipo_dispositivo")
    op.drop_table("tipo_accion")
    op.drop_table("rol")
    op.drop_table("objeto_afectado")
    # ### end Alembic commands ###
